[meta]
# site title, show in <title>
title = "GoDoc"

# subtitle, words after title, in description
subtitle = "Just For Writing"

# print in html <meta>
keyword = "golang,python,docker"

# print in html <meta>
desc = "golang,python,docker"

# build links for feed, sitemap
domain = "godoc.me"

# root path for site# if empty, build as http://{domain}/
root = "http://localhost:9899/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "en"


[[nav]]
link = "/"
title = "Home"
i18n = "home"
# set nav to active status
hover = "index"
blank = false

[[nav]]
link = "/archive.html"
title = "Archive"
i18n = "archive"
hover = "archive"

[[nav]]
link = "/favorites.html"
title = "Favorites"
i18n = "favorites"
hover = "favorites"

[[nav]]
link = "/about.html"
title = "About"
i18n = "about"
hover = "about"

[[author]]
name = "miaoboyong"
email = "mbywin@gmail.com"
url = "http://godoc.me"
avatar = "@media/author.png"
bio = ""

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = "mbywin"
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""
